auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Green Apple
url: http://joenali.github.io
feed: /atom.xml
author_info: <a href="http://joenali.github.io/">Green Apple</a>
